### PR TITLE
Remove jquery dependency

### PR DESCRIPTION
**Pull request by yaymukund**
Hi, thank you for creating this tiny library. This PR removes the jquery dependency to make it even tinier.

### CODE REVIEW

**Comment by bartlett705** [comment]
Hi @eirslett ! Pinging you as the only contributor to this handy library. 

Any chance we could get a look at this Pull Request? I see in the README that such a PR should theoretically be welcomed, but I understand this package hasn't been very active lately.

**Comment by eirslett** [comment]
It would be welcomed, but I don't work at TIDAL anymore, so I don't have merge rights. I suggest that you fork the repo and maintain it. Or just copy-paste the code snippet, it's only 98 lines of code so you can commit it to your git repository.

**Comment by enjikaka** [comment]
Merged it now and bumped the version. But only you @eirslett can publish the new version to npm. 👻

**Comment by bartlett705** [comment]
@enjikaka Thank you! 🎉 

@eirslett we were planning on using an internal fork, but wanted to explore up-streaming first if possible. Thanks for the response, and apologies for pinging you based on an outdated indicatior of ownership 🙂

**Comment by eirslett** [comment]
@enjikaka I added you (jeremy-tidal) as owner now.

**Comment by enjikaka** [comment]
Great. I'll release it on monday when I'm back on the work computer!

**Comment by yaymukund** [comment]
Thank you @enjikaka! Any chance we could get that new release? 👀

**Comment by enjikaka** [comment]
Sorry for the delay guys, forgot. 🙈 Version 1.0.2 is available on NPM now! :) https://www.npmjs.com/package/ie11-scroll-into-view

**Comment by bartlett705** [comment]
No worries on the delay @enjikaka - thanks for the help 💯

**Pull request merged**
